#105: Stop supporting PHP versions < 5.3.4
Older versions do not include php-fpm by default.

diff --git a/puppet/modules/custom/profiles/files/box/phpmanager/scripts/phpmanager b/puppet/modules/custom/profiles/files/box/phpmanager/scripts/phpmanager
--- a/puppet/modules/custom/profiles/files/box/phpmanager/scripts/phpmanager
+++ b/puppet/modules/custom/profiles/files/box/phpmanager/scripts/phpmanager
@@ -104,6 +104,13 @@ command_use() {
     fi
 
     if [[ ! -d "/opt/php/$VERSION" ]] || [[ "${VERSION}" == "master" ]] ; then
+        SHORT=$(sub_getshortversion $VERSION)
+
+        if [[ "$SHORT" -lt 5304 ]] ; then
+            echo "PHP versions older than 5.3.4 are no longer supported."
+            exit 1
+        fi
+
         if [[ "${VERSION}" == "master" ]] ; then
             echo -e "\033[33mRebuilding master ..\e[0m"
         else
@@ -122,6 +129,8 @@ command_use() {
         command_install $VERSION
     fi
 
+    sudo service php-fpm stop > /dev/null 2>&1
+
     # Install the binaries
     for BINARY in "${BINARIES[@]}"
     do
@@ -135,7 +144,8 @@ command_use() {
 
     sudo rm -f /opt/php/php-fpm.sock
     sudo ln -s "/run/php/${VERSION}-fpm.sock" /opt/php/php-fpm.sock
-    sudo service php-fpm restart
+
+    sudo service php-fpm start > /dev/null 2>&1
 
     echo -e "Installed binaries. PHP version is now:\n"
     php -v
@@ -152,6 +162,13 @@ command_install() {
 
     if [[ "${VERSION:0:4}" != "php-" ]] && [[ "${VERSION}" != "master" ]]; then
         VERSION="php-${VERSION}"
+    fi
+
+    SHORT=$(sub_getshortversion $VERSION)
+
+    if [[ "$SHORT" -lt 5304 ]] ; then
+        echo "PHP versions older than 5.3.4 are no longer supported."
+        exit 1
     fi
 
     LOGFILE="/tmp/phpmanager-build-${VERSION}.log"
@@ -176,7 +193,6 @@ command_install() {
     git checkout $VERSION  &> /dev/null
 
     # Setup the PATH to include legacy build tools if needed
-    SHORT=$(sub_getshortversion $VERSION)
     if [[ "$SHORT" -lt 5419 ]] ; then
         export PATH=/opt/bison-2.2/bin:/opt/flex-2.5.4/bin:$PATH
     else
@@ -270,6 +286,8 @@ command_restore() {
         exit 0
     fi
 
+    sudo service php-fpm stop > /dev/null 2>&1
+
     for BINARY in "${BINARIES[@]}"
     do
         sudo /usr/bin/update-alternatives --auto "${BINARY}" &> /dev/null
@@ -282,7 +300,7 @@ command_restore() {
 
     sudo rm -f /opt/php/php-fpm.sock
     sudo ln -s "/run/php/php7.1-fpm.sock" /opt/php/php-fpm.sock
-    sudo service php-fpm restart
+    sudo service php-fpm start > /dev/null 2>&1
 
     echo -e "Restored PHP, version is now: \n"
     php -v
@@ -477,7 +495,7 @@ sub_getoptions() {
     if [[ "$SHORT" -lt 5213 ]] ; then
         if [[ ! -d "/opt/mysql-5.1.73-linux-x86_64-glibc23/" ]] ; then
             echo "Downloading MySQL 5.1.73 dependencies .."
-            wget -O /tmp/mysql-5.1.73.tar.gz --no-check-certificate https://downloads.skysql.com/archives/mysql-5.1/mysql-5.1.73-linux-x86_64-glibc23.tar.gz
+            wget -O /tmp/mysql-5.1.73.tar.gz --no-check-certificate http://mirrors.ukfast.co.uk/sites/ftp.mysql.com/Downloads/MySQL-5.1/mysql-5.1.73-linux-x86_64-glibc23.tar.gz
             sudo tar -xf /tmp/mysql-5.1.73.tar.gz -C /opt/
             sudo chown -R root:root /opt/mysql-5.1.73-linux-x86_64-glibc23
             sudo ln -s /opt/mysql-5.1.73-linux-x86_64-glibc23/lib /opt/mysql-5.1.73-linux-x86_64-glibc23/lib/x86_64-linux-gnu
@@ -557,9 +575,9 @@ sub_setupini() {
     # according to the docs at http://be2.php.net/dl but for most builds this isn't the case.
     # So let's make sure we properly set the extension_dir directive :
     EXTENSION=$(sub_getextensionnumber $VERSION)
-    echo "extension_dir=/opt/php/${VERSION}/lib/php/extensions/no-debug-non-zts-${EXTENSION}/" | sudo tee "/opt/php/${VERSION}/etc/conf.d/99-custom.ini"
+    echo "extension_dir=/opt/php/${VERSION}/lib/php/extensions/no-debug-non-zts-${EXTENSION}/" | sudo tee "/opt/php/${VERSION}/etc/conf.d/99-custom.ini" > /dev/null
 
-    cat /home/vagrant/php.ini-template | sudo tee -a "/opt/php/${VERSION}/etc/conf.d/99-custom.ini"
+    cat /home/vagrant/php.ini-template | sudo tee -a "/opt/php/${VERSION}/etc/conf.d/99-custom.ini" > /dev/null
 
     sudo chown vagrant:vagrant "/opt/php/${VERSION}/lib/php.ini"
     sudo chown -R vagrant:vagrant "/opt/php/${VERSION}/etc/conf.d"
@@ -673,12 +691,12 @@ sub_getextensionnumber() {
     echo $EXTENSION
 }
 
-# Make sure the PHP source is available
+# Make sure the PHP source and dependencies are available
 sub_checksource() {
     if [[ ! -d "$SOURCE/.git" ]] ; then
         echo -e "\033[33mCould not find PHP source!\e[0m"
         echo "Looks like this is the first time you run this script and/or the PHP source is missing."
-        echo "Please wait while we clone the PHP Git repo. Depending on your internet connection this could take a while .. "
+        echo "Please wait while we clone the PHP Git repo and install the required dependencies. Depending on your internet connection this could take a while .. \n"
 
         git clone "git://git.php.net/php-src.git" "$SOURCE"
 
@@ -688,7 +706,7 @@ sub_checksource() {
 
     if [[ ! -d "$SOURCE_XDEBUG/.git" ]] ; then
         echo -e "\033[33mCould not find Xdebug source!\e[0m"
-        echo "Please wait while we clone the Xdebug source. Depending on your internet connection this could take a while .. "
+        echo "Please wait while we clone the Xdebug source. Depending on your internet connection this could take a while .. \n"
 
         git clone "https://github.com/xdebug/xdebug.git" "$SOURCE_XDEBUG"
 
@@ -727,6 +745,13 @@ sub_getcurrent() {
 sub_configurefpm() {
   VERSION="$1"
 
+  SHORT=$(sub_getshortversion $VERSION)
+  if [[ "$SHORT" -ge 5309 ]]; then
+    PROCESSMANAGER=ondemand
+  else
+    PROCESSMANAGER=static
+  fi
+
   CONTENTS="[global]
 pid = /run/php/${VERSION}-fpm.pid
 
@@ -736,12 +761,15 @@ group = www-data
 listen = /run/php/${VERSION}-fpm.sock
 listen.owner = www-data
 listen.group = www-data
-pm = ondemand
+pm = ${PROCESSMANAGER}
 pm.max_children = 5
-pm.process_idle_timeout = 10s;
 pm.max_requests = 250"
 
-  echo "$CONTENTS" | sudo tee --append  "/opt/php/${VERSION}/etc/php-fpm.conf" > /dev/null
+  if [[ $PROCESSMANAGER == "ondemand" ]]; then
+    CONTENTS="${CONTENTS}\npm.process_idle_timeout = 10s\n"
+  fi
+
+  echo -e "$CONTENTS" | sudo tee --append  "/opt/php/${VERSION}/etc/php-fpm.conf" > /dev/null
 
 }
 # Check if a value exists in an array
